name: Docker image CI

on:
  push:
    tags: '*'

jobs:
  build:
    name: Build and publish Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Remove "_Docker" suffix from GitHub repository name to use it as image name
      id: docker_image_name
      run: |
        REPO_NAME=$(echo "${GITHUB_REPOSITORY}" | sed 's/_Docker$//' | tr '[:upper:]' '[:lower:]')
        echo "repo_name=${REPO_NAME}" >> $GITHUB_ENV

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and publish Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        file: ./Dockerfile
        push: true
        tags: |
          ghcr.io/${{ env.repo_name }}:${{ github.ref_name }}
